project Sprint 13 - working with branches add-controllers
EllaStani/java-shareit pull request #1
Opened 2022-12-27 21:49 UTC by EllaStani

2023-01-01 21:32 UTC, alexache requested changes

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto saveNewItem(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody ItemDto itemDto) {
Хорошо бы добавить аннотацию @Valid и соответствующие валидации на полях ДТО

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private void validationCreateItem(Long userId, ItemDto itemDto) {
Будет проще через валидацию полей ДТО класса

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        for (Item item : items) {
(опционально) можно переделать в функциональном стиле через items.stream().map(ItemMapper::mapToItemDto)

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return userItems == null ? null : ItemMapper.mapToListItemDto(userItems);
(опционально) Мне кажется, null никогда не возвращается, то есть проверка возможно лишняя

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getItemByUserIdAndItemId(@PathVariable long itemId) {
Какое-то противоречивое название метода, где же тут userId?

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final UserService userService;
Будет  проще, если добавлять зависимость на userRepository нежели сервис, нам ведь не обязательно получать ДТО объекты и интерфейс сервиса не будет загроможден вспомогательными методами для других сервисов

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkingExistUser(userId);
Для чего эта строка ниже, если валидация юзера уже сделана?

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        ;
Хорошо бы подчищать такие строки

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    List<ItemDto> getAllItems();
Для чего такой метод?

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemRepository.java
> +    public List<Item> getAllItems() {
Не уверен, что такой метод нужен

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemRepository.java
> +        List<Item> allItems = getAllItems();
Это очень неоптимальный способ, лучше завести вторую дублирующую мапу, но с itemId -> Item маппингом

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemRepository.java
> +                    .filter(p -> (p.getName().toLowerCase().contains(text.toLowerCase())
text.toLowerCase лучше сделать единожды до цикла

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner;
В модели лучше бы хранить обхект User вместо просто айди

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private void validationCreateUser(UserDto userDto) {
Лучше делать через валидацию полей ДТО

2023-01-01 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserRepository.java
> +        emails.remove(users.get(userId).getEmail());
можно бы получать объект User на методу remove, и оттуда уже брать email

2023-01-08 13:06 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto saveNewItem(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody ItemDto itemDto) {
выполнено

2023-01-08 13:06 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private void validationCreateItem(Long userId, ItemDto itemDto) {
выполнено

2023-01-08 13:07 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        for (Item item : items) {
спасибо, исправила

2023-01-08 13:07 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return userItems == null ? null : ItemMapper.mapToListItemDto(userItems);
да, действительно

2023-01-08 13:08 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getItemByUserIdAndItemId(@PathVariable long itemId) {
исправила

2023-01-08 13:09 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemRepository.java
> +        List<Item> allItems = getAllItems();
спасибо, переделала

2023-01-08 13:09 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner;
ок

2023-01-08 13:09 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private void validationCreateUser(UserDto userDto) {
выполнила

2023-01-08 13:10 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserRepository.java
> +        emails.remove(users.get(userId).getEmail());
спасибо, переделала

2023-01-09 08:59 UTC, alexache approved these changes

2023-01-09 08:59 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +//@Validated
Закомментированный код лучше удалять. Git все равно помнит что где было

2023-01-09 08:59 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        UserDto userDto = checkingExistUser(userId);
(опционально) вот здесь и минус использования userService. Сначала получается User, потом конвертируется в UserDto, затем снова конвертируется в User, а можно бы обойтись прямым вызовом к userRepository

2023-01-09 08:59 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private User owner;
В ДТО объектах не должно быть ссылки на модели (User) - тут либо UserDto, либо userId

2023-01-15 11:03 UTC, merged