project Sprint 15 – working with branch add-bookings ver 1.0
EllaStani/java-shareit pull request #2
Opened 2023-01-26 18:32 UTC by EllaStani

2023-01-27 15:58 UTC, alexache requested changes

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    Item item;
Не хватает модификаторов доступа

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
Эта аннотация включает в себя @EqualsAndHashcode, которая некорректна для JPA моделей. Лучше использовать @Getter/@Setter

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    List<BookingOutDto> getAllBooking(String state, long booker, String type);
Ни к чему такая гибкость с type, лучше пусть будет 2 разных метода - getAllBookingsByOwner / getAllBookingsByBooker

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingJpaRepository.java
> +    @Query(value = "select * " +
Многие из этих запросов можно реализовать не через нативные запросы, а через query creation from method names, то есть через названия методов - findByOwnerId(), findByBookerId()

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (state.equals("ALL")) {
Лучше бы завести enum для BookingState и написать switch-case, а так же type разделить на 2 разных метода. Сложно ориентироваться, когда так много if-else-if-else

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInDto.java
> +/**
Комментарии можно подчищать

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInDto.java
> +    private LocalDateTime start;
Не помешает валидация на поля - например, что время не в прошлом

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutDto.java
> +    BookingBookerDto booker;
Модификаторы доступа

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkingExistItem(itemId);
Проверку существования вещи и метод получения вещи модно объединить в один вызов  findById().orElseThrow()

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Item> searchItems = itemRepository.findAll().stream()
Почему поиск не сделать SQL запросом? Будет эффективнее чем парсинг

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkingExistItem(itemId);
Тут тоже проверки лучше соединить с получением по айди

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = itemRepository.findById(itemId).get();
Много повторных запросов к базе поулчается

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comments.java
> +    Item item;
Молдификатор доступа

2023-01-27 15:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        //return users == null ? null : UserMapper.mapToListUserDto(users);
Комментарии лучше удалять

2023-01-29 12:22 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/booking/BookingJpaRepository.java
> +    @Query(value = "select * " +
findByBookerId() - получилось сделать, а findByOwnerId() - нет, запрос с join. Не знаю как.

2023-01-30 20:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingJpaRepository.java
> +    @Query(value = "select * " +
Не вижу проблемы, если owner есть как поле в модели, то запрос легко пишется с указанием поля модели - findByOwnerId сделает поиск с помощью поля id в модели User поля Owner

2023-01-30 21:32 UTC, alexache requested changes

2023-01-30 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingJpaRepository.java
> +            "order by b.end_date DESC ", nativeQuery = true)
Если по какой-то причине не поулчается написать без query, то желательно хотя бы без native, чтобы немного больше обезопасить себя в правильности запроса

2023-01-30 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  public class Item {
Кстати, у поля owner не хватает джоина на модель User

2023-01-30 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comments.java
>  public class Comments {
Модель должна называться в единственном числе - Comment

2023-01-30 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingBookerDto.java
> -@Data
На всякий случай уточню, что комментарий про @Data касался только моделей JPA, а не ДТО классов. Для ДТО классов нет проблемы использовать @Data

2023-01-30 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingStatus.java
> +    CANCELED,
В одном Enum смешались 2 несвязанных перечисления, так не стоит делать, лучше это будут 2 разных енама

2023-01-30 21:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInDto.java
> +/**
Этот комментарий остался. TODO нет смысла оставлять

2023-01-31 13:04 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/booking/BookingJpaRepository.java
> +    @Query(value = "select * " +
Спасибо, разобралась с запросами, все Query переделала

2023-01-31 13:05 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/booking/BookingJpaRepository.java
> +            "order by b.end_date DESC ", nativeQuery = true)
Спасибо, все @Query переделала

2023-01-31 13:08 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  public class Item {
теперь нет @Query - нет джоинов. Или я что-то не правильно поняла, пыталась спросить в пачке, но так как времени нет, решила отправить.

2023-01-31 21:40 UTC, EllaStani commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  public class Item {
Все переделала.

2023-02-01 11:24 UTC, alexache approved these changes

2023-02-03 18:16 UTC, merged